### ISSUE TITLE
Date not part of article link in All Posts

### ISSUE THREAD

**Issue by symandria** [SilasReinagel/silasreinagel.github.io#10]
### Context
OS/Browser: Windows 10 / Microsoft Edge<br>
Page URL: https://silasreinagel.github.io/all

### Problem Description
Current Behavior: Clicking on date for related article does not take you to article.<br>
(Optional) Expected Behavior: Hovering over date or clicking on date should show or take you to the corresponding article.

**Comment by SilasReinagel** [comment]
@symandria Bug accepted. Payment sent.
