### ISSUE TITLE
Icons at top of page links inconsistently

### ISSUE THREAD

**Issue by ThePhantomStranger** [SilasReinagel/silasreinagel.github.io#11]
## Context
OS/Browser: Windows 7 / Chrome Version 67.0.3396.99

Page URL: https://silasreinagel.github.io

## Problem Description
Current Behavior: Only clicking on your logo brings you back to the index.

Expected Behavior: All icons at the top of the page (logo, name, and photo) should have consistent behavior, either all linking to the index or not.

**Comment by SilasReinagel** [comment]
@ThePhantomStranger Bug accepted. Payment sent.
