### ISSUE TITLE
Arrows Break Form when passing 1080p - Microsoft Edge

### ISSUE THREAD

**Issue by symandria** [SilasReinagel/silasreinagel.github.io#9]
### Context
OS/Browser: Windows 10 / Microsoft Edge<br>
Page URL: https://silasreinagel.github.io/page2/

### Problem Description
Screenshot of Issue: [picture 1 - microsoft edge approx width 2560x1440 - arrows mismatch](https://user-images.githubusercontent.com/27328984/42906151-14dd57ee-8a8f-11e8-9a44-049c43954d6b.png)<br>
Current Behavior: Arrows look different and aren't on same line.<br>

**Comment by SilasReinagel** [comment]
@symandria Bug accepted. Payment sent.

**Comment by SilasReinagel** [comment]
Fixed with https://github.com/SilasReinagel/silasreinagel.github.io/commit/46647c79c8760fc40538101602d0f755626fa20b
